[package]
name = "polkadot-runtime-wrappers"
authors = [ "OpenZeppelin" ]
description = "Wrappers with Sensible Defaults for constructing Polkadot Parachain Runtimes"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/OpenZeppelin/polkadot-runtime-wrappers"
readme = "README.md"
version = "0.0.1"

[dependencies]
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.10.0" }
scale-info = { version = "2.10.0", default-features = false }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.10.0" }
sp-version = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.10.0" }

[features]
default = [ "std" ]
std = [
	"frame-support/std",
	"scale-info/std",
	"sp-std/std",
	"sp-version/std",
]
