[package]
name = "polkadot-runtime-wrappers"
authors = [ "OpenZeppelin" ]
description = "Wrappers with Sensible Defaults for constructing Polkadot Parachain Runtimes"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/OpenZeppelin/polkadot-runtime-wrappers"
readme = "README.md"
version = "0.0.1"

[dependencies]
cumulus-pallet-parachain-system = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.10.0" }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.10.0" }
frame-support-procedural = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.10.0" }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.10.0" }
pallet-balances = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.10.0" }
pallet-proxy = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.10.0" }
pallet-timestamp = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.10.0" }
parachain-info = { package = "staging-parachain-info", git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.10.0" }
parity-scale-codec = { version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = [ "derive" ] }
sp-version = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, tag = "polkadot-v1.10.0" }

[features]
default = [ "std" ]
std = [
    "cumulus-pallet-parachain-system/std",
	"frame-support-procedural/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"pallet-proxy/std",
	"pallet-timestamp/std",
	"parachain-info/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"sp-version/std",
]
async-backing = []
experimental = []
